<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="EPRURYAW0080" name="com.epam.olga_eremkina.testng.QuadrateTest" tests="20" failures="0" timestamp="17 Jul 2018 12:52:51 GMT" time="0.033" errors="1">
  <testcase name="quadrateLenght" time="0.001" classname="com.epam.olga_eremkina.testng.QuadrateTest"/>
  <testcase name="quadrateLenght" time="0.001" classname="com.epam.olga_eremkina.testng.QuadrateTest"/>
  <testcase name="quadrateLenght" time="0.001" classname="com.epam.olga_eremkina.testng.QuadrateTest"/>
  <testcase name="quadrateLenght" time="0.005" classname="com.epam.olga_eremkina.testng.QuadrateTest"/>
  <testcase name="quadrateSquare" time="0.000" classname="com.epam.olga_eremkina.testng.QuadrateTest"/>
  <testcase name="quadrateSquare" time="0.001" classname="com.epam.olga_eremkina.testng.QuadrateTest"/>
  <testcase name="quadrateSquare" time="0.001" classname="com.epam.olga_eremkina.testng.QuadrateTest"/>
  <testcase name="quadrateLenght" time="0.002" classname="com.epam.olga_eremkina.testng.QuadrateTest"/>
  <testcase name="quadrateLenght" time="0.001" classname="com.epam.olga_eremkina.testng.QuadrateTest"/>
  <testcase name="quadrateLenght" time="0.001" classname="com.epam.olga_eremkina.testng.QuadrateTest"/>
  <testcase name="quadrateLenght" time="0.002" classname="com.epam.olga_eremkina.testng.QuadrateTest"/>
  <testcase name="quadrateLenght" time="0.012" classname="com.epam.olga_eremkina.testng.QuadrateTest">
    <error type="org.testng.TestException" message="
Method QuadrateTest.quadrateLenght(int)[pri:0, instance:com.epam.olga_eremkina.testng.QuadrateTest@523884b2] should have thrown an exception of type class java.lang.RuntimeException">
      <![CDATA[org.testng.TestException: 
Method QuadrateTest.quadrateLenght(int)[pri:0, instance:com.epam.olga_eremkina.testng.QuadrateTest@523884b2] should have thrown an exception of type class java.lang.RuntimeException
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:80)
at org.testng.internal.Invoker.considerExceptions(Invoker.java:1140)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:615)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- quadrateLenght -->
  <testcase name="quadrateSquare" time="0.000" classname="com.epam.olga_eremkina.testng.QuadrateTest"/>
  <testcase name="quadrateSquare" time="0.002" classname="com.epam.olga_eremkina.testng.QuadrateTest"/>
  <testcase name="quadrateSquare" time="0.000" classname="com.epam.olga_eremkina.testng.QuadrateTest"/>
  <testcase name="quadrateLenght" time="0.001" classname="com.epam.olga_eremkina.testng.QuadrateTest"/>
  <testcase name="quadrateSquare" time="0.000" classname="com.epam.olga_eremkina.testng.QuadrateTest"/>
  <testcase name="quadrateSquare" time="0.001" classname="com.epam.olga_eremkina.testng.QuadrateTest"/>
  <testcase name="quadrateSquare" time="0.001" classname="com.epam.olga_eremkina.testng.QuadrateTest"/>
  <testcase name="quadrateSquare" time="0.000" classname="com.epam.olga_eremkina.testng.QuadrateTest"/>
</testsuite> <!-- com.epam.olga_eremkina.testng.QuadrateTest -->
